import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'workout_model.dart';

class WorkoutData {
  // Predefined cardio workouts
  static List<Map<String, dynamic>> cardioWorkouts = [
    {
      'name': 'Running',
      'icon': FontAwesomeIcons.personRunning,
      'color': Colors.blue,
      'description': 'High-intensity running with interval training',
      'exercises': [
        {'name': 'Warm-up Jog', 'duration': '5 min', 'intensity': 'Low'},
        {'name': 'Sprint Interval', 'duration': '30 sec', 'intensity': 'High'},
        {'name': 'Recovery Jog', 'duration': '1 min', 'intensity': 'Medium'},
        {'name': 'Sprint Interval', 'duration': '30 sec', 'intensity': 'High'},
        {'name': 'Recovery Jog', 'duration': '1 min', 'intensity': 'Medium'},
        {'name': 'Cool Down', 'duration': '5 min', 'intensity': 'Low'},
      ],
      'duration': '30 min',
      'calories': 320,
      'difficulty': 'Medium',
    },
    {
      'name': 'Cycling',
      'icon': FontAwesomeIcons.bicycle,
      'color': Colors.green,
      'description': 'Endurance cycling with hill climbs',
      'exercises': [
        {'name': 'Warm-up Cycling', 'duration': '5 min', 'intensity': 'Low'},
        {'name': 'Flat Terrain', 'duration': '10 min', 'intensity': 'Medium'},
        {'name': 'Hill Climb', 'duration': '5 min', 'intensity': 'High'},
        {'name': 'Descent Recovery', 'duration': '3 min', 'intensity': 'Low'},
        {'name': 'Hill Climb', 'duration': '5 min', 'intensity': 'High'},
        {'name': 'Flat Terrain', 'duration': '10 min', 'intensity': 'Medium'},
        {'name': 'Cool Down', 'duration': '7 min', 'intensity': 'Low'},
      ],
      'duration': '45 min',
      'calories': 400,
      'difficulty': 'Medium',
    },
    {
      'name': 'Swimming',
      'icon': FontAwesomeIcons.personSwimming,
      'color': Colors.purple,
      'description': 'Mixed stroke swimming workout',
      'exercises': [
        {'name': 'Warm-up Freestyle', 'duration': '5 min', 'intensity': 'Low'},
        {'name': 'Freestyle Laps', 'duration': '10 min', 'intensity': 'Medium'},
        {'name': 'Breaststroke Laps', 'duration': '10 min', 'intensity': 'Medium'},
        {'name': 'Backstroke Laps', 'duration': '10 min', 'intensity': 'Medium'},
        {'name': 'Sprint Freestyle', 'duration': '5 min', 'intensity': 'High'},
        {'name': 'Recovery Laps', 'duration': '5 min', 'intensity': 'Low'},
        {'name': 'Cool Down', 'duration': '5 min', 'intensity': 'Low'},
      ],
      'duration': '60 min',
      'calories': 500,
      'difficulty': 'Hard',
    },
    {
      'name': 'Walking',
      'icon': FontAwesomeIcons.personWalking,
      'color': Colors.orange,
      'description': 'Brisk walking with posture focus',
      'exercises': [
        {'name': 'Slow Walk', 'duration': '3 min', 'intensity': 'Low'},
        {'name': 'Brisk Walking', 'duration': '10 min', 'intensity': 'Medium'},
        {'name': 'Uphill Walking', 'duration': '5 min', 'intensity': 'Medium-High'},
        {'name': 'Recovery Walk', 'duration': '2 min', 'intensity': 'Low'},
        {'name': 'Cool Down', 'duration': '3 min', 'intensity': 'Low'},
      ],
      'duration': '20 min',
      'calories': 180,
      'difficulty': 'Easy',
    },
    {
      'name': 'HIIT Cardio',
      'icon': FontAwesomeIcons.bolt,
      'color': Colors.red,
      'description': 'High Intensity Interval Training',
      'exercises': [
        {'name': 'Warm-up', 'duration': '3 min', 'intensity': 'Low'},
        {'name': 'Jumping Jacks', 'duration': '45 sec', 'intensity': 'High'},
        {'name': 'Rest', 'duration': '15 sec', 'intensity': 'Low'},
        {'name': 'Mountain Climbers', 'duration': '45 sec', 'intensity': 'High'},
        {'name': 'Rest', 'duration': '15 sec', 'intensity': 'Low'},
        {'name': 'Burpees', 'duration': '45 sec', 'intensity': 'High'},
        {'name': 'Rest', 'duration': '15 sec', 'intensity': 'Low'},
        {'name': 'High Knees', 'duration': '45 sec', 'intensity': 'High'},
        {'name': 'Rest', 'duration': '15 sec', 'intensity': 'Low'},
        {'name': 'Cool Down', 'duration': '3 min', 'intensity': 'Low'},
      ],
      'duration': '25 min',
      'calories': 300,
      'difficulty': 'Hard',
    },
    {
      'name': 'Jump Rope',
      'icon': FontAwesomeIcons.stopwatch,
      'color': Colors.amber,
      'description': 'Intense jump rope cardio training',
      'exercises': [
        {'name': 'Warm-up', 'duration': '3 min', 'intensity': 'Low'},
        {'name': 'Basic Jump', 'duration': '2 min', 'intensity': 'Medium'},
        {'name': 'Rest', 'duration': '30 sec', 'intensity': 'Low'},
        {'name': 'Alternate Foot Jump', 'duration': '2 min', 'intensity': 'Medium'},
        {'name': 'Rest', 'duration': '30 sec', 'intensity': 'Low'},
        {'name': 'Double Under Attempts', 'duration': '1 min', 'intensity': 'High'},
        {'name': 'Rest', 'duration': '30 sec', 'intensity': 'Low'},
        {'name': 'High Knees Jump', 'duration': '1 min', 'intensity': 'High'},
        {'name': 'Rest', 'duration': '30 sec', 'intensity': 'Low'},
        {'name': 'Speed Jump', 'duration': '1 min', 'intensity': 'High'},
        {'name': 'Cool Down', 'duration': '2 min', 'intensity': 'Low'},
      ],
      'duration': '15 min',
      'calories': 200,
      'difficulty': 'Medium',
    },
    {
      'name': 'Stair Climbing',
      'icon': FontAwesomeIcons.mountain,
      'color': Colors.cyan,
      'description': 'Stair climbing for leg strength and cardio',
      'exercises': [
        {'name': 'Warm-up Walk', 'duration': '3 min', 'intensity': 'Low'},
        {'name': 'Steady Climb', 'duration': '5 min', 'intensity': 'Medium'},
        {'name': 'Double Step Climb', 'duration': '2 min', 'intensity': 'High'},
        {'name': 'Recovery Walk', 'duration': '1 min', 'intensity': 'Low'},
        {'name': 'Speed Climb', 'duration': '3 min', 'intensity': 'High'},
        {'name': 'Recovery Walk', 'duration': '1 min', 'intensity': 'Low'},
        {'name': 'Lateral Climb', 'duration': '2 min', 'intensity': 'Medium-High'},
        {'name': 'Cool Down', 'duration': '3 min', 'intensity': 'Low'},
      ],
      'duration': '20 min',
      'calories': 240,
      'difficulty': 'Medium-Hard',
    },
    {
      'name': 'Rowing',
      'icon': FontAwesomeIcons.ship,
      'color': Colors.teal,
      'description': 'Full-body rowing workout for endurance',
      'exercises': [
        {'name': 'Warm-up Row', 'duration': '5 min', 'intensity': 'Low'},
        {'name': 'Steady Pace', 'duration': '8 min', 'intensity': 'Medium'},
        {'name': 'Power Strokes', 'duration': '3 min', 'intensity': 'High'},
        {'name': 'Recovery Row', 'duration': '2 min', 'intensity': 'Low'},
        {'name': 'Speed Intervals', 'duration': '5 min', 'intensity': 'High'},
        {'name': 'Steady Pace', 'duration': '5 min', 'intensity': 'Medium'},
        {'name': 'Cool Down', 'duration': '3 min', 'intensity': 'Low'},
      ],
      'duration': '30 min',
      'calories': 350,
      'difficulty': 'Medium',
    },
    {
      'name': 'Elliptical',
      'icon': FontAwesomeIcons.personWalking,
      'color': Colors.deepPurple,
      'description': 'Low-impact elliptical trainer workout',
      'exercises': [
        {'name': 'Warm-up', 'duration': '5 min', 'intensity': 'Low'},
        {'name': 'Forward Stride', 'duration': '7 min', 'intensity': 'Medium'},
        {'name': 'Increased Resistance', 'duration': '5 min', 'intensity': 'Medium-High'},
        {'name': 'Backward Stride', 'duration': '3 min', 'intensity': 'Medium'},
        {'name': 'Hill Climb (High Resistance)', 'duration': '5 min', 'intensity': 'High'},
        {'name': 'Recovery Pace', 'duration': '2 min', 'intensity': 'Low'},
        {'name': 'Speed Intervals', 'duration': '5 min', 'intensity': 'High'},
        {'name': 'Cool Down', 'duration': '3 min', 'intensity': 'Low'},
      ],
      'duration': '35 min',
      'calories': 320,
      'difficulty': 'Medium',
    },
  ];

  // Predefined strength workouts
  static List<Map<String, dynamic>> strengthWorkouts = [
    {
      'name': 'Upper Body Strength',
      'icon': FontAwesomeIcons.dumbbell,
      'color': Colors.indigo,
      'description': 'Focus on chest, shoulders, and arms',
      'exercises': [
        {'name': 'Push-ups', 'sets': 3, 'reps': '12-15', 'rest': '60 sec'},
        {'name': 'Dumbbell Shoulder Press', 'sets': 3, 'reps': '10-12', 'rest': '60 sec'},
        {'name': 'Bicep Curls', 'sets': 3, 'reps': '12', 'rest': '45 sec'},
        {'name': 'Tricep Dips', 'sets': 3, 'reps': '12-15', 'rest': '45 sec'},
        {'name': 'Bent-over Rows', 'sets': 3, 'reps': '10-12', 'rest': '60 sec'},
      ],
      'duration': '45 min',
      'calories': 350,
      'difficulty': 'Medium',
    },
    {
      'name': 'Core Workout',
      'icon': FontAwesomeIcons.person,
      'color': Colors.teal,
      'description': 'Strengthen your abdominal and lower back muscles',
      'exercises': [
        {'name': 'Plank', 'sets': 3, 'duration': '45 sec', 'rest': '30 sec'},
        {'name': 'Russian Twists', 'sets': 3, 'reps': '16 (8 each side)', 'rest': '30 sec'},
        {'name': 'Leg Raises', 'sets': 3, 'reps': '12-15', 'rest': '30 sec'},
        {'name': 'Mountain Climbers', 'sets': 3, 'duration': '30 sec', 'rest': '30 sec'},
        {'name': 'Superman Hold', 'sets': 3, 'duration': '30 sec', 'rest': '30 sec'},
      ],
      'duration': '30 min',
      'calories': 250,
      'difficulty': 'Medium',
    },
    {
      'name': 'Lower Body Strength',
      'icon': FontAwesomeIcons.personWalking,
      'color': Colors.deepOrange,
      'description': 'Focus on legs and glutes',
      'exercises': [
        {'name': 'Squats', 'sets': 4, 'reps': '15', 'rest': '60 sec'},
        {'name': 'Lunges', 'sets': 3, 'reps': '12 each leg', 'rest': '45 sec'},
        {'name': 'Calf Raises', 'sets': 3, 'reps': '20', 'rest': '30 sec'},
        {'name': 'Glute Bridges', 'sets': 3, 'reps': '15', 'rest': '45 sec'},
        {'name': 'Step Ups', 'sets': 3, 'reps': '10 each leg', 'rest': '45 sec'},
      ],
      'duration': '40 min',
      'calories': 320,
      'difficulty': 'Medium',
    },
  ];
} 